#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Vocabilis.Droid.Resource", IsApplication=true)]

namespace Vocabilis.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::Vocabilis.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::Vocabilis.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_discard = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_favorite = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_volume_on = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_fa_play = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_fa_play_circle_o = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_fa_star = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_fa_star_o = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon_default = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int speaking_icon_ = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int volume_up_phone = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
